# Use an official Icecast image from the Docker Hub
FROM sebp/icecast

# Copy your Icecast configuration file into the container
COPY icecast.xml /etc/icecast2/icecast.xml

# Expose the Icecast port
EXPOSE 8000